import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import Nav from "./navbar/nav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" grid grid-cols-[20%_auto] p-0 bg-zinc-900"   >
        <nav className="border border-t-0 border-r-0 border-l-0  col-start-1 col-end-3 h-30 p-10 bg-zinc-900">
          < Nav />
        </nav>
        <aside className="bg-zinc-800  h-200 " >
          <ul className=" leading-10">
            <li className="hover:bg-cyan-900 px-4 py-1 "><a href="/">Defult</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1 "><a href="/home">Home</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1 "><a href="/about">About</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1"><a href="/contact">Contact</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1"><a href="">Contact</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1"><a href="">Galary</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1"><a href="">Catagory</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1"><a href="">Produktin</a></li>
            <li className="hover:bg-cyan-900 px-4 py-1"><a href="">Contact</a></li>
          </ul>
        </aside>
        {children}
      </body>
    </html>
  );
}
