import type { Metadata } from "next";
import "./globals.css";

import { SiSololearn } from "react-icons/si";
import { CiSearch } from "react-icons/ci";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex stiky top-0 left-0 w-full justify-between items-center py-6 px-4 bg-gradient-to-r from-[#E47A5C] to-[#3AA199] text-white shadow-md">
          <div className="text-3xl">
            <SiSololearn />
          </div>
          <div className="flex gap-4 text-lg font-bold">
            <p className="hover:text-[#50b4ac] cursor-grabbing">HTML</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">CSS</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">JAVASCRIPT</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">WEB APIs</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">All</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">Learn</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">Tools</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">About</p>
            <p className="hover:text-[#50b4ac] cursor-grabbing">Blog</p>
          </div>
          <div className="flex items-center px-1 py-1 rounded-2xl hover:bg-gradient-to-r hover:from-[#E47A5C] hover:to-[#3AA199] cursor-grabbing transition">
            <input type="search" className="outline-none text-sm italic" placeholder="Search..." />
            <CiSearch className=" ml-2" />
          </div>
        </header>
        <div className="grid grid-cols-[20%_auto] min-h-screen">
          <aside className="bg-gray-100 p-6">
            <ul className="space-y-2 font-bold text-gray-700 text-center">
              <li><a href="/html" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">HTML</a></li>
              <li><a href="/css" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">CSS</a></li>
              <li><a href="/javascript" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C] hover:to-[#fffff]">JavaScript</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C] ">React</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Next.js</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Tailwind CSS</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Python</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Django</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Flask</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">C++</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">C#</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Java</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Kotlin</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">PHP</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Laravel</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Node.js</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Express.js</a></li>
              <li><a href="#" className="block w-full py-2 rounded-xl hover:text-white hover:bg-gradient-to-r hover:from-[#E47A5C]">Git & GitHub</a></li>
            </ul>
          </aside>
          {children}
        </div>
      </body>
    </html>
  );
}